language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

before_script: cd ksweb

install:
  - "pip install -e ksweb[testing]"
  - "pip install coveralls"
  - "pip install codecov"

script:
  - "nosetests -v --with-coverage"

after_success:
  - coveralls
  - codecov
